#!/bin/sh
#*********************************************************************#
#                                                                     #
#                             Active-DVI                              #
#                                                                     #
#                   Projet Cristal, INRIA Rocquencourt                #
#                                                                     #
#  Copyright 2003 Institut National de Recherche en Informatique et   #
#  en Automatique.  All rights reserved.  This file is distributed    #
#  under the terms of the GNU Lesser General Public License.          #
#                                                                     #
#  Jun Furuse, Didier Rémy and Pierre Weis.                           #
#  Contributions by Roberto Di Cosmo, Didier Le Botlan,               #
#  Xavier Leroy, and Alan Schmitt.                                    #
#                                                                     #
#  Based on Mldvi by Alexandre Miquel.                                #
#*********************************************************************#

# $Id$
# Pierre Weis

# Command to generate thumbnails image arguments

HHEIGHT=230
HWIDTH=170

IMGS=$*

#echo Resizing source images
for i in $IMGS
do
 file=`basename $i`;
 dir=`dirname $i`;
 echo "convert $i -geometry ${HWIDTH}x$HHEIGHT! $dir/thumb_$file"
 #read x
 convert $i -geometry ${HWIDTH}x$HHEIGHT! $dir/thumb_$file
done

